apiVersion: v1
kind: Service
metadata:
  name: service-commits
spec:
  selector:
    app: commits-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer  # or NodePort, depending on your setup