apiVersion: v1
kind: Service
metadata:
  name: service-issues
spec:
  selector:
    app: issues-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer  # or NodePort, depending on your setup