apiVersion: v1
kind: Service
metadata:
  name: service-pullreqs
spec:
  selector:
    app: pullreqs-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: LoadBalancer  # or NodePort, depending on your setup